.read './db/structure.sql'
.read './db/elections/2009_european/voting_locations_2016.sql'

insert or ignore into election_periods(id, name) values (11, 'Избори за членове на европейския парламент 2009');
insert or ignore into elections (id, name, round1_date, election_period_id) values
(30, 'Избори за членове на европейския парламент 2009', '2009-06-07', 11);

insert into temp_protocols (election_id, section_code, total_voters, voters_by_signature, ballots_in_box, invalid_ballots_in_box, valid_ballots_in_box) select 30, section_id, total_voters, voters_by_signature, ballots_in_box, invalid_ballots, ballots_in_box-invalid_votes from _2009_european_protocols;
drop table _2009_european_protocols;

insert or ignore into location_neighborhoods (location_id, neighborhood) select distinct location_id, replace(neighborhood, '"', '') from voting_locations_2016 where neighborhood != '';

insert or ignore into sections (election_period_id, location_id, section_code) select 11, (select id from locations where locations.ekatte=_2009_european_sections.ekatte), section_id from _2009_european_sections;
drop table _2009_european_sections;

insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 1, party_1_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 2, party_1_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 3, party_1_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 4, party_1_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 5, party_1_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 6, party_1_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 7, party_1_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 8, party_1_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 9, party_1_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 10, party_1_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 11, party_1_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 12, party_1_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 13, party_1_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 14, party_1_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 15, party_1_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 16, party_1_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 1, 17, party_1_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 1, party_2_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 2, party_2_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 3, party_2_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 4, party_2_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 5, party_2_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 6, party_2_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 7, party_2_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 8, party_2_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 9, party_2_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 10, party_2_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 11, party_2_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 12, party_2_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 13, party_2_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 14, party_2_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 15, party_2_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 16, party_2_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 2, 17, party_2_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 1, party_3_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 2, party_3_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 3, party_3_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 4, party_3_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 5, party_3_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 6, party_3_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 7, party_3_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 8, party_3_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 9, party_3_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 10, party_3_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 11, party_3_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 12, party_3_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 13, party_3_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 14, party_3_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 15, party_3_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 16, party_3_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 3, 17, party_3_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 1, party_4_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 2, party_4_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 3, party_4_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 4, party_4_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 5, party_4_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 6, party_4_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 7, party_4_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 8, party_4_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 9, party_4_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 10, party_4_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 11, party_4_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 12, party_4_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 13, party_4_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 14, party_4_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 15, party_4_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 16, party_4_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 4, 17, party_4_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 1, party_5_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 2, party_5_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 3, party_5_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 4, party_5_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 5, party_5_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 6, party_5_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 7, party_5_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 8, party_5_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 9, party_5_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 10, party_5_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 11, party_5_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 12, party_5_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 13, party_5_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 14, party_5_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 15, party_5_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 16, party_5_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 5, 17, party_5_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 1, party_6_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 2, party_6_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 3, party_6_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 4, party_6_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 5, party_6_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 6, party_6_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 7, party_6_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 8, party_6_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 9, party_6_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 10, party_6_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 11, party_6_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 12, party_6_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 13, party_6_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 14, party_6_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 15, party_6_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 16, party_6_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 6, 17, party_6_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 1, party_7_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 2, party_7_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 3, party_7_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 4, party_7_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 5, party_7_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 6, party_7_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 7, party_7_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 8, party_7_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 9, party_7_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 10, party_7_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 11, party_7_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 12, party_7_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 13, party_7_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 14, party_7_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 15, party_7_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 16, party_7_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 7, 17, party_7_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 1, party_8_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 2, party_8_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 3, party_8_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 4, party_8_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 5, party_8_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 6, party_8_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 7, party_8_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 8, party_8_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 9, party_8_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 10, party_8_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 11, party_8_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 12, party_8_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 13, party_8_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 14, party_8_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 15, party_8_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 16, party_8_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 8, 17, party_8_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 1, party_9_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 2, party_9_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 3, party_9_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 4, party_9_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 5, party_9_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 6, party_9_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 7, party_9_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 8, party_9_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 9, party_9_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 10, party_9_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 11, party_9_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 12, party_9_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 13, party_9_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 14, party_9_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 15, party_9_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 16, party_9_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 9, 17, party_9_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 1, party_10_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 2, party_10_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 3, party_10_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 4, party_10_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 5, party_10_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 6, party_10_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 7, party_10_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 8, party_10_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 9, party_10_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 10, party_10_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 11, party_10_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 12, party_10_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 13, party_10_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 14, party_10_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 15, party_10_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 16, party_10_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 10, 17, party_10_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 1, party_11_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 2, party_11_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 3, party_11_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 4, party_11_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 5, party_11_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 6, party_11_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 7, party_11_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 8, party_11_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 9, party_11_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 10, party_11_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 11, party_11_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 12, party_11_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 13, party_11_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 14, party_11_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 15, party_11_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 16, party_11_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 11, 17, party_11_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 1, party_12_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 2, party_12_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 3, party_12_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 4, party_12_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 5, party_12_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 6, party_12_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 7, party_12_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 8, party_12_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 9, party_12_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 10, party_12_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 11, party_12_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 12, party_12_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 13, party_12_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 14, party_12_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 15, party_12_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 16, party_12_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 12, 17, party_12_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 1, party_13_candidate_1 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 2, party_13_candidate_2 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 3, party_13_candidate_3 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 4, party_13_candidate_4 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 5, party_13_candidate_5 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 6, party_13_candidate_6 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 7, party_13_candidate_7 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 8, party_13_candidate_8 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 9, party_13_candidate_9 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 10, party_13_candidate_10 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 11, party_13_candidate_11 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 12, party_13_candidate_12 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 13, party_13_candidate_13 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 14, party_13_candidate_14 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 15, party_13_candidate_15 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 16, party_13_candidate_16 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 17, party_13_candidate_17 from _2009_european_preferences;
insert into temp_preferences (election_id, section_code, party_id, candidate_id, valid_votes) select 30, section_id, 13, 1, party_13_candidate_17 from _2009_european_preferences;
drop table _2009_european_preferences;

insert or ignore into voting_locations (location_id, cik_address, address, lat, lng, postcode, location_neighborhood_id) select location_id, address, replace(formatted_address, '"', ''), lat, lng, replace(postcode, '"', ''), (select id from location_neighborhoods where location_neighborhoods.location_id=voting_locations_2016.location_id and neighborhood=replace(voting_locations_2016.neighborhood, '"', '')) from voting_locations_2016;

update sections set address_id=(select id from voting_locations join voting_locations_2016 on voting_locations_2016.address=voting_locations.cik_address and sections.section_code=voting_locations_2016.section_id) where election_period_id=11 and address_id is null;
insert into protocols (election_id, round, section_id, section_type, total_voters, voters_by_signature, ballots_in_box, invalid_ballots_in_box, valid_ballots_in_box, no_one) select election_id, round, sections.id, section_type, total_voters, voters_by_signature, ballots_in_box, invalid_ballots_in_box, valid_ballots_in_box, no_one from temp_protocols join sections on sections.section_code=temp_protocols.section_code;
drop table temp_protocols;
insert into preferences (election_id, section_id, party_id, candidate_id, valid_votes, machine_voting)  select election_id, sections.id, party_id, candidate_id, valid_votes, temp_preferences.machine_voting from temp_preferences join sections on sections.section_code=temp_preferences.section_code;
drop table temp_preferences;
vacuum;